services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/golfclubqap?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Keyin2025
      SERVER_PORT: 8081
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: golfclubqap
      MYSQL_USER: root
      MYSQL_PASSWORD: Keyin2025
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: