services:
  myapp-main:
    image: golfclubqap:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golfclubqap
      # - spring.datasource.url=jdbc:mysql://bptracking.czo6a2muuk9c.us-east-2.rds.amazonaws.com/bptracking
      - spring.datasource.password=Keyin2025
      - spring.datasource.username=root